### ISSUE TITLE
медіазапити

### ISSUE THREAD

**Issue by pecourses** [mishakravchenia/my-project#8]
https://github.com/mishakravchenia/my-project/blob/7babac6c26a59890df1aef9b81fb3ae2d684ed8a/assets/css/styles.css#L269-L290
- якщо властивості змінюються для одних і тих самих брекпойнтів, то це прописують разом:
```css
@media screen and (max-width: 600px) {
  nav a + a {
    display: none;
  }

  .conteiner-one {
    grid-template-columns: 1fr;
  }

  .wrapper {
    width: 100%;
  }

  .container-two {
    grid-template-columns: 1fr;
  }

  .user-card {
    width: 100%;
  }
}

```
